config/routes.rb
Graffitizer::Application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  devise_for :users

  get "home/index"
  root to: 'home#index'

  resources :throwups, only: [:new, :create, :show]
  resources :messages, only: [:new, :create, :index, :show]
  resources :chats, only: [:index, :create]
  resource :user, as: :present_user, controller: 'present_user', only: [:show, :edit, :update]

  resources :throwups, only: [:new, :create, :index, :show] do
    resources :comments, only: [:new, :create, :update, :show]
    resource :like, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index] do
    resources :throwups, module: 'users', only: [:index]
  end

  resources :battle_entries do
    resource :battle_vote, only: [:create, :destroy]
  end

  resources :battles, only: [:new, :create, :index, :show] do
    resources :battle_entries, only: [:new, :create, :index, :show]
  end
end

app/models/throwup.rb
class Throwup < ActiveRecord::Base
  has_attached_file :attachment, styles: {
    thumb: '150x150>',
    large: '500x500>'
  }

  validates_attachment_content_type :attachment, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  validates :attachment, presence: true, if: :youtube_nil?
  validates :youtube, presence: true, if: :attachment_nil?

  belongs_to :user
  belongs_to :battle_entry
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes

  scope :legals, -> { where(:category_id => '1') }
  scope :illegals, -> { where(:category_id => '2') }
  scope :trains, -> { where(:category_id => '3') }
  scope :sketches, -> { where(:category_id => '4') }
  scope :stencils, -> { where(:category_id => '5') }
  scope :tags, -> { where(:category_id => '6') }
  scope :various, -> { where(:category_id => '7') }




  def attachment_nil?
    !attachment?
  end

  def youtube_nil?
    youtube.nil?
  end

  def youtube_id
    if youtube[/youtu\.be\/([^\?]*)/]
      $1
    else
      youtube[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      $5
    end
  end
end

app/controllers/throwups_controller.rb
class ThrowupsController < ApplicationController
  before_filter :authenticate_user!,
    :only => [:create, :edit]

  def new
    @throwup = Throwup.new
  end

  def index
    @throwups = Throwup.paginate :page => params[:page], :per_page => 12, :order => "id DESC"
    @legals = Throwup.legals.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"
    @illegals = Throwup.illegals.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"
    @trains = Throwup.trains.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"
    @sketches = Throwup.sketches.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"
    @stencils = Throwup.stencils.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"
    @tags = Throwup.tags.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"
    @various = Throwup.various.paginate :page => params[:pge], :per_page => 12, :order => "id DESC"

  end

  def create
    @throwup = current_user.throwups.new(throwup_params)
    @throwup.save
    if @throwup.save
      redirect_to throwups_path
    else
      render acttion: :new
    end
  end

  def show
    @throwup = Throwup.find(params[:id])
    @counter = @throwup.likes.count
    @comment = Comment.new
    @next_throwup = Throwup.where("id >?", @throwup.id).first
    @prev_throwup = Throwup.where("id <?", @throwup.id).last
    if current_user.present?
      @like = current_user.likes.build(throwup_id: @throwup.id)
    else
      nil
    end
  end

  private

    def throwup_params
      params.require(:throwup).permit(:content, :youtube, :city, :crew, :date, :attachment, :category_id)
    end
end

app/controllers/users/throwups_controller.rb
module Users
  class ThrowupsController < ApplicationController

    def index
      @user = User.find(params[:user_id])
      @throwups = @user.throwups.paginate :page => params[:page], 
        :per_page => 12, :order => "id DESC"

    end

  end
end

app/helpers/throwup_helper.rb
module ThrowupHelper
  def youtube_thumbnail(youtube_id)
    "http://img.youtube.com/vi/#{youtube_id}/1.jpg"
  end
  def youtube_player(youtube_id)
    %Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}.html_safe
    #%iframe{ :width => 640, :height => 390, :frameborder => "0", :src => "//www.youtube.com/embed/#{youtube_id}" }
  end
end

app/views/throwups/_likes.html.haml
= "#{@likes_counter}"

app/views/throwups/create.html.haml
%p
  = 'Powinieneś dodać zdjęcie albo youtub!'
.form
  = simple_form_for @throwup do |f|
    = f.input :content, as: :text
    = f.input :attachment
    = f.input :youtube
    = f.submit "Throw it up!"

app/views/throwups/index.html.haml
.main-page.with-top-margin
  .span2
    %div.dl-horizontal.with-top-margin.tabbable.tabs-below
      %ul.nav.nav-pills.nav-stacked
        %li.active#myTab
          %a{href: "#tab1", "data-toggle" => "tab"} Wszystkie
        %li#myTab
          %a{href: "#tab2", "data-toggle" => "tab"} Legale
        %li#myTab
          %a{href: "#tab3", "data-toggle" => "tab"} Nielegale
        %li#myTab
          %a{href: "#tab4", "data-toggle" => "tab"} Pociągi
        %li#myTab
          %a{href: "#tab5", "data-toggle" => "tab"} Kartki
        %li#myTab
          %a{href: "#tab6", "data-toggle" => "tab"} Szablony
        %li#myTab
          %a{href: "#tab7", "data-toggle" => "tab"} Tagi
        %li#myTab
          %a{href: "#tab8", "data-toggle" => "tab"} Różne
  .t-ups-section.centered.span8
    %p.bolded
      Wrzuty
      .tab-content
        #tab1.tab-pane.active
          - @throwups.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @throwups
        #tab2.tab-pane
          - @legals.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @legals
        #tab3.tab-pane
          - @illegals.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @illegals
        #tab4.tab-pane
          - @trains.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @trains
        #tab5.tab-pane
          - @sketches.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @sketches
        #tab6.tab-pane
          - @stencils.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @stencils
        #tab7.tab-pane
          - @tags.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @tags
        #tab8.tab-pane
          - @various.each_slice(4) do |s|
            %table
              %tr.throwups-line
                - s.each do |t|
                  %td.t-up-index
                    %p
                      = link_to "#{t.user.name}", user_path(t.user.id)
                      wrzucił:
                    %p
                    - if t.attachment?
                      = link_to (image_tag t.attachment.url(:thumb)), throwup_path(t.id)
                    - if t.youtube?
                      = link_to (image_tag youtube_thumbnail(t.youtube_id)), throwup_path(t.id)
                    %p.pull-right.t_up-counter
                      - if t.likes.any?
                        %i.icon.fa.fa-star
                      - else
                        %i.icon.fa.fa-star-o
                      = t.likes.count
                      - if t.comments.any?
                        %i.icon.fa.fa-comment
                      - else
                        %i.icon.fa.fa-comment-o
                      = t.comments.count
          = will_paginate @various

app/views/throwups/new.html.haml
.span3.form.with-top-margin.centered
  = simple_form_for @throwup do |f|
    = f.input :attachment, label: 'Nowy wrzut'
    = f.input :youtube, label: false, placeholder: 'Możesz dać tu link do youtuba'
    = f.input :content, as: :text, label: false, placeholder: 'Możesz też coś napisać'
    = f.association :category, label: 'Kategoria:', as: :radio_buttons, include_blank: false
    = f.submit 'Wrzuć!'

app/views/throwups/show.html.haml
.throwup_section.centered.span8
  %br
  %br
  .span1.next_throwup.pull-left
    - if !@next_throwup.nil?
      = link_to main_app.throwup_path(@next_throwup), class: 'btn navigation-button', title: 'Następny' do
        %i.icon.fa.fa-arrow-circle-o-left.fa-2x
  .span1.prev_throwup.pull-right
    - if !@prev_throwup.nil?
      = link_to main_app.throwup_path(@prev_throwup), class: 'btn navigation-button', title: 'Poprzedni' do
        %i.icon.fa.fa-arrow-circle-o-right.fa-2x
  %p
    - if @throwup.attachment?
      = button_tag(image_tag(@throwup.attachment.url(:large)), { data: { target: "#modal_throwup", toggle: "modal" } })
    - if @throwup.youtube?
      %p
      %p
        = youtube_player(@throwup.youtube_id)
  %p
    = @throwup.content
  %p
    = link_to "#{@throwup.user.name}", user_path(@throwup.user_id)
    = link_to '- wyślij wiadomość', new_message_path(recipient_id: @throwup.user.id)
    .likes_section
      = render partial: 'likes/like', locals: { counter: @counter, throwup: @throwup }
  .comments_section
    = render partial: 'comments/index', locals: { throwup: @throwup }
.modal.fade#modal_throwup{ tabindex: 1 }
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
    %h3
      = @throwup.content
  .modal-body
    = image_tag @throwup.attachment.url
  .modal-footer
    %a.btn{href: "#"} Close